Repository evolvedbinary/fusion-studio-extension, pull requests merged in 2020-08, with the labels that each got.

#210 Change download location of XAR for Travis to avoid GitHub limits
  .travis.yml
Labels: cla-signed

#209 check api version before connecting
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/classes/error.ts
  fusion-studio-extension/src/common/api.ts
Labels: cla-signed

#212 Update to version 0.2.0 of the API
  .travis.yml
Labels: cla-signed, enhancement

#213 Fix database names in README.md
  README.md
Labels: cla-signed, enhancement

#207 Deprecated tree
  cypress/integration/operations_spec.js
  cypress/integration/tree_spec.js
  cypress/support/index.d.ts
  cypress/support/index.js
  cypress/support/utils.js
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/browser/label-provider-contribution.ts
  fusion-studio-extension/src/browser/widget/drag.ts
  fusion-studio-extension/src/classes/node.ts
  fusion-studio-extension/src/common/api.ts
  package.json
Labels: cla-signed

#218 Better error handling for evaluating XQuery
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/browser/dialogs/basic.ts
  fusion-studio-extension/src/browser/widget/eval.tsx
Labels: cla-signed

#220 Fix renaming object
  cypress/integration/operations_spec.js
  fusion-studio-extension/src/browser/core.ts
Labels: cla-signed

#215 Update API to 0.3.0
  .travis.yml
Labels: bug, cla-signed

#221 Properties dialog
  cypress/integration/operations_spec.js
  cypress/integration/properties.js
  cypress/support/index.d.ts
  cypress/support/utils.js
  fusion-studio-extension/src/browser/commands.ts
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/browser/dialogs/properties-dialog.ts
  fusion-studio-extension/src/browser/dialogs/user-dialog.ts
  fusion-studio-extension/src/classes/autocomplete.ts
  fusion-studio-extension/src/classes/template.ts
  fusion-studio-extension/src/common/templates/restxq.ts
  fusion-studio-extension/src/common/templates/rng.ts
  fusion-studio-extension/src/common/templates/xml.ts
  fusion-studio-extension/src/common/templates/xq.ts
  fusion-studio-extension/src/common/templates/xqm.ts
  fusion-studio-extension/src/common/templates/xsd.ts
  fusion-studio-extension/src/common/templates/xslt.ts
Labels: [zube]: Backlog, cla-signed

#196 Yarn should be installed via NPM - correct the README.md
  README.md
Labels: cla-signed

#224 Formatting XQuery evaluation result
  fusion-studio-extension/src/browser/widget/_eval.scss
  fusion-studio-extension/src/browser/widget/eval.tsx
  fusion-studio-extension/src/common/api.ts
Labels: cla-signed

#225 Update to latest API for CI tests
  .travis.yml
Labels: cla-signed, enhancement

#226 Error handling
  fusion-studio-extension/src/browser/dialogs/alert-dialog.ts
  fusion-studio-extension/src/browser/widget/eval.tsx
  fusion-studio-extension/src/classes/error.ts
  fusion-studio-extension/src/common/api.ts
Labels: cla-signed, enhancement

#227 Connections list improvements
  cypress/integration/properties.js
  fusion-studio-extension/src/browser/commands.ts
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/common/api.ts
Labels: bug, cla-signed, enhancement

#228 fix: pager not working properly
  fusion-studio-extension/src/browser/widget/eval.tsx
Labels: cla-signed

#230 Nodes height
  browser-app/package.json
  cypress/integration/properties.js
  electron-app/package.json
  fusion-studio-extension/package.json
  fusion-studio-extension/src/browser/core.ts
  fusion-studio-extension/src/browser/widget/main.tsx
  yarn.lock
Labels: cla-signed

#229 fix: versions conflict in theia dpendencies
  browser-app/package.json
  electron-app/package.json
  fusion-studio-extension/package.json
Labels: cla-signed
